version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: vehicles
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d vehicles"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 5s
    restart: unless-stopped


  minio:
    image: minio/minio:latest
    command: server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
    volumes:
      - miniodata:/data
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - network.host=0.0.0.0   # <-- IMPORTANT: garder 0.0.0.0 ici
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf http://localhost:9200/ || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: unless-stopped

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: voiture-backend:latest
    environment:
      DATABASE_URL: "postgresql+psycopg2://app:changeme@postgres:5432/vehicles"
      ELASTIC_HOST: "http://elasticsearch:9200"
      REDIS_URL: "redis://redis:6379/0"
      MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ACCESS: "minio"
      MINIO_SECRET: "minio123"
      ES_INDEX: "vehicles"
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "127.0.0.1:8000:8000"   # <-- bind explicite sur localhost de l'hôte
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: voiture-frontend:latest
    ports:
      - "127.0.0.1:5173:80"     # <-- bind frontend sur localhost de l'hôte (nginx inside:80)
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
  miniodata:
  esdata:
